//%attributes = {"publishedWeb":true}
  //G-Proc:ClearLtrArrays
CLEAR VARIABLE:C89(aPartyType)
CLEAR VARIABLE:C89(aPLName)
CLEAR VARIABLE:C89(aPFName)
CLEAR VARIABLE:C89(aFirm)
CLEAR VARIABLE:C89(aStAdd)
CLEAR VARIABLE:C89(aCity)
CLEAR VARIABLE:C89(aState)
CLEAR VARIABLE:C89(aZip)
CLEAR VARIABLE:C89(aPartyLang)
